### PR TITLE
update Sci_Position.h for N++ 8.2.2

### LINKED ISSUE #135: Sci_Position changes in upcoming Notepad++ 8.2.2 release
See here:

https://community.notepad-plus-plus.org/topic/22471/recompile-your-x64-plugins-with-new-header

You use the `SCI_GETTEXTRANGE` call which is affected.  May just need to update your `Sci_Position.h` file with latest from Notepad++ repo:

+ notepad-plus-plus/scintilla/include/Sci_Position.h

Cheers.

### PR DESCRIPTION
**Pull request by vinsworldcom**
Just updated Sci_Position.h file to see if this fixes the issue.

Fix #135

### CODE REVIEW

**Comment by morbac** [comment]
I've included the fix in [release 3.1.1.11](https://github.com/morbac/xmltools/releases/tag/3.1.1.11).

**Comment by xomx** [comment]
@morbac 

This PR is incomplete. For your XMLTools plugin is not enough to update only the Sci_Position.h.

There are other problems in the plugin code in connection with the upcoming N++ 8.2.2+ support for 2GB+ files. One of them I mentioned [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11104#issuecomment-1028444228).

To reproduce the crash:
- download a 8.2.2 RC5 x64 build of N++, e.g. [this](http://download.notepad-plus-plus.org/repository/8.x/8.2.2.RC5/npp.8.2.2.portable.x64.7z)
- add your latest patched  [3.1.1.11 x64 plugin](https://github.com/morbac/xmltools/releases/download/3.1.1.11/XMLTools-3.1.1.11-x64.zip)
- start N++
- open a 2GB+ text file (you can use e.g. [this](https://drive.google.com/file/d/11r2sdOFUzSino7lrq6QveBhensqTFcCf/view?usp=sharing))
- select menu Plugins -> XMLTools -> Pretty print
- Plugin Crash msbbox: XMLTools.dll just crashed in runPluginCommand(size_t i : 36)

If you want to, I could tomorrow check the XMLTools plugin codebase for the remaining 2GB+ problematic parts and then create another PR to fix these problems.

**Comment by morbac** [comment]
The fix embedded in 3.1.1.11 was required to avoid crash on "small" files.

Now I agree with you that this patch is by far not sufficient for 2GB+ files. I did some checks tonight and I think I could identify the crash root cause. I'll try to fix it as soon as possible.

**Comment by xomx** [comment]
Ok. If you will need a tester, let me know.
There is also this N++ plugintemplate Scintilla.h [update](https://github.com/npp-plugins/plugintemplate/commit/e5b7487da9feccf00ae89952f714e0a4c6352675#diff-7447add2b532fe5ff9c05370f83d7c7e7d8e5b4ec2322825badce19049d8eafd).
And thanks for your very useful plugin.

**Comment by morbac** [comment]
Work is in progress. I've built this first pre-version of 3.1.1.12 which fix some issues you observed with 2GB+ files:

[3.1.1.12 alpha.zip](https://github.com/morbac/xmltools/files/8008573/3.1.1.12.alpha.zip)

I still have to improve error report when annotation mode is selected. I also have to check that modifications have not negative impact on encoding support.

**Comment by xomx** [comment]
So far so good, no more crashing :-)

**Pull request merged**
