### PR TITLE
curl -> 7.62.0 updated for appveyor build

### PR DESCRIPTION
**Pull request by chcg**
See https://ci.appveyor.com/project/chcg/xmltools/builds/20473552 + artifacts enabled, e.g.
https://ci.appveyor.com/project/chcg/xmltools/builds/20473552/job/xh72p1ah09j65rbw/artifacts

### CODE REVIEW

**Comment by chcg** [comment]
@morbac You need to register this project at appveyor to enable the CI build, see https://www.appveyor.com/docs/

**Comment by chcg** [comment]
In the meantime even https://curl.haxx.se/changes.html#7_62_0 is available with some fixes for CVE issues.

**Comment by chcg** [comment]
@morbac Seems curl is no longer used. Is this correct? Seems this PR could be closed then without merge.

**Comment by morbac** [comment]
Yes, it's true. Libcurl was used to check for plugin updates, but with the new plugin admin tool, I guess this is useless.

**Pull request closed without merging**
